[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[rpc_endpoints]
arb = "${ARB_RPC_URL}"

[invariant]
# runs = 10
fail_on_revert = true
