[profile.default]
cache_path = 'cache_forge'
ffi = true
fs_permissions = [{access = "read", path = "./out"}]
libs = ['node_modules', 'lib']
optimizer_runs = 200
out = 'out'
src = 'contracts'
test = 'test'

ast = true
builder = true
extra_output = ["storageLayout"]

[rpc_endpoints]
arb = "${ARB_RPC_URL}"

[invariant]
fail_on_revert = true
